### PR TITLE
Update to use the torchbox version of personalisation

### PR DESCRIPTION
**Pull request by todd-dembrey**
@nathanbegbie This points the repo at the static and dynamic version of wagtail personalisation

### CODE REVIEW

**Comment by todd-dembrey** [comment]
@nathanbegbie Will your deployment team sort out how this is installed in the box?

**Comment by nathanbegbie** [comment]
@todd-dembrey Yep, should do. I've contacted them to check how we can do this - do you think we could move this into a branch of the same name, instead of develop?

**Comment by nathanbegbie** [comment]
Actually, never mind - as long as this is the correct reference I'll create my own branch.

**Comment by nathanbegbie** [comment]
Handled in https://github.com/praekelt/molo.surveys/pull/45 instead.
Closing this issue.

**Pull request closed without merging**
